<?php
/**
 * Small Class Sniff
 *
 * This is not a small class
 */
class SmallClassSniffTest
{
    /**
     * small method
     */
    public function smallMethod()
    {
        /**
         * This space intentionally left blank
         *
         *
         *
         *
         *
         *
         *
         */
    }

    /**
     * small method, big doc block
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     *
     */
    public function smallMethodBigDocBlock()
    {
        /**
         * This space intentionally left blank
         *
         *
         *
         *
         *
         *
         *
         */
    }

    /**
     * Oversize method
     */
    public function oversizeMethod()
    {
        /**
         * This space intentionally left blank
         *
         *
         *
         *
         *
         *
         *
         *
         */
    }
}
